# Generated by Django 4.1.7 on 2023-03-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coins_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coins',
            new_name='Coin',
        ),
    ]
