# Generated by Django 4.1.7 on 2023-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_coin_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
    ]
