# Generated by Django 4.1.7 on 2023-04-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
