# Generated by Django 4.1.7 on 2023-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
