# Generated by Django 4.1.7 on 2023-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_ownedcoins_ownedcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
