# Generated by Django 4.1.7 on 2023-04-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_coin_price'),
        ('main', '0011_order_type'),
    ]

    operations = [
    ]
