# Generated by Django 4.1.7 on 2023-04-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_account_balance_address'),
        ('main', '0012_merge_0007_alter_coin_price_0011_order_type'),
    ]

    operations = [
    ]
