# Generated by Django 4.1.7 on 2023-04-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_merge_20230405_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedcoin',
            name='price',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
    ]