# Generated by Django 4.1.7 on 2023-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_ticket_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedcoin",
            name="price",
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
