# Generated by Django 4.1.7 on 2023-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primaryk", models.IntegerField(max_length=10)),
                ("question", models.CharField(max_length=250)),
                ("answer", models.CharField(max_length=100)),
                ("option_one", models.CharField(max_length=100)),
                ("option_two", models.CharField(max_length=100)),
                ("option_three", models.CharField(blank=True, max_length=100)),
                ("option_four", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
